package tn.esprit.projetpidev.domain.enums;

public enum Role {
    COMPERS, COMPSITEOWNERS, EQUIPEMENTPROVIEDERS, GUIDE, COACH,
    PARTENERS,EVENT_ORGANIZER, SPONSORS, ADMIN, DELIVERYAGENT, CAMPSITEMANAGER
}
